# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pl_powiat', '0005_auto_20160326_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(max_length=15)),
                ('label', models.CharField(max_length=150)),
                ('powiat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pl_powiat.Powiat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
