# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl_gmina', '0002_fetch_gminas_wikidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmina',
            name='pending_revision',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmina',
            name='reviewed_revision',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
