# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiDataEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(max_length=15)),
                ('label', models.CharField(max_length=150)),
                ('reviewed_revision', models.CharField(max_length=15)),
                ('pending_revision', models.CharField(max_length=15)),
            ],
        ),
    ]
