# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl_powiat', '0002_fetch_powiats'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiat',
            name='miato_na_prawach_powiatu',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
