# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pl_powiat', '0004_fetch_miasto_na_prawach_powiatu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powiat',
            old_name='miato_na_prawach_powiatu',
            new_name='miasto_na_prawach_powiatu',
        ),
    ]
