# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(max_length=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Poland')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
