# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl_wojewodztwo', '0002_fetch_wojewodztwo_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='wojewodztwo',
            name='label',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
