# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_family', models.CharField(max_length=20)),
                ('wiki_lang', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=1000)),
                ('new_id', models.CharField(max_length=15)),
                ('rev_id', models.CharField(max_length=15)),
            ],
        ),
    ]
